# Generated by Django 5.2.7 on 2025-10-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoanalysis',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chat.dialog'),
        ),
    ]
